{"cause":"Test exception thrown!"}GET